// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatMessage struct {
	ID       pgtype.UUID        `json:"id"`
	StreamID pgtype.UUID        `json:"stream_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Message  string             `json:"message"`
	SentAt   pgtype.Timestamptz `json:"sent_at"`
}

type Stream struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Title           pgtype.Text        `json:"title"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	Status          string             `json:"status"`
	HlsPath         pgtype.Text        `json:"hls_path"`
	RecordingPath   pgtype.Text        `json:"recording_path"`
	RecordingStatus string             `json:"recording_status"`
	PeakViewers     int32              `json:"peak_viewers"`
	TotalViewers    int32              `json:"total_viewers"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	SrsClientID     pgtype.Int4        `json:"srs_client_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type StreamAnalytic struct {
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	Date          pgtype.Date `json:"date"`
	TotalSeconds  int32       `json:"total_seconds"`
	PeakViewers   int32       `json:"peak_viewers"`
	UniqueViewers int32       `json:"unique_viewers"`
}

type StreamViewer struct {
	StreamID  pgtype.UUID        `json:"stream_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ClientID  string             `json:"client_id"`
	FirstSeen pgtype.Timestamptz `json:"first_seen"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	GoogleID       string             `json:"google_id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	StreamKeyHash  string             `json:"stream_key_hash"`
	StreamTitle    pgtype.Text        `json:"stream_title"`
	StreamCategory pgtype.Text        `json:"stream_category"`
	IsLive         bool               `json:"is_live"`
	LiveSince      pgtype.Timestamptz `json:"live_since"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
