// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
