// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, google_id, email, name, avatar_url, stream_key_hash, stream_title, stream_category, is_live, live_since, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.StreamKeyHash,
		&i.StreamTitle,
		&i.StreamCategory,
		&i.IsLive,
		&i.LiveSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
